Fixes proposition
SmartHomiesPW/SmartHomeApp pull request #7
Opened 2023-12-30 14:06 UTC by JanPalmer

2023-12-30 18:07 UTC, JanPalmer reviewed
g

2024-01-01 23:11 UTC, Adioos5 commented
Coś się popsuło. Dostaję error 'Value cannot be null. Parameter name: collection'. Spróbuj odpalić sobie u siebie backend oraz serwer we Flasku w PyCharmie w trakcie testowania apki i sprawdź czy u ciebie działa pobieranie danych z backendu. Załączam kod serwera we Flasku:

from flask import Flask, jsonify
import datetime
import json

app = Flask(__name__)
class Light:
    def __init__(self, lightId, isOn):
        self.lightId = lightId
        self.isOn = isOn

class HumiditySensor:
    def __init__(self, sensorId, humidity, dateTime):
        self.sensorId = sensorId
        self.humidity = humidity
        self.dateTime = dateTime

class TemperatureSensor:
    def __init__(self, sensorId, temperature, dateTime):
        self.sensorId = sensorId
        self.temperature = temperature
        self.dateTime = dateTime

class SunlightSensor:
    def __init__(self, sensorId, lightValue, dateTime):
        self.sensorId = sensorId
        self.lightValue = lightValue
        self.dateTime = dateTime

light1 = Light(lightId=0, isOn=1)
light2 = Light(lightId=1, isOn=1)
light3 = Light(lightId=2, isOn=1)
light4 = Light(lightId=3, isOn=0)

hum1 = HumiditySensor(sensorId=0, humidity=44, dateTime='2020')
hum2 = HumiditySensor(sensorId=1, humidity=22, dateTime='2020')

tem1 = TemperatureSensor(sensorId=0, temperature=11, dateTime='2020')
tem2 = TemperatureSensor(sensorId=1, temperature=33, dateTime='2020')

sun1 = SunlightSensor(sensorId=0, lightValue=55, dateTime='2020')
sun2 = SunlightSensor(sensorId=1, lightValue=66, dateTime='2020')

hums = [hum1, hum2]
tems = [tem1, tem2]
suns = [sun1, sun2]

lights = [light1, light2, light3, light4]

@app.route('/sensors/humidity', methods=['GET'])
def getHumiditySensorsStates():
    global hums
    json_data = json.dumps([{'sensorId': hum.sensorId, 'humidity': hum.humidity, 'dateTime': hum.dateTime} for hum in hums])
    return json_data

@app.route('/sensors/temperature', methods=['GET'])
def getTemperatureSensorsStates():
    global tems
    json_data = json.dumps([{'sensorId': tem.sensorId, 'temperature': tem.temperature, 'dateTime': tem.dateTime} for tem in tems])
    return json_data

@app.route('/sensors/light', methods=['GET'])
def getSunlightSensorsStates():
    global suns
    json_data = json.dumps([{'sensorId': sun.sensorId, 'lightValue': sun.lightValue, 'dateTime': sun.dateTime} for sun in suns])
    return json_data

@app.route('/lights/states', methods=['GET'])
def getLightsStates():
    global lights
    json_data = json.dumps([{'lightId': light.lightId, 'isOn': light.isOn} for light in lights])
    return json_data

@app.route('/lights/set/<int:lightId>/<int:isOn>', methods=['GET'])
def setLightState(lightId, isOn):
    global lights
    lights[lightId].isOn = isOn
    print("Light [" + str(lightId) + "] set to " + str(isOn))
    json_data = json.dumps([{'lightId': light.lightId, 'isOn': light.isOn} for light in lights])
    return json_data

if __name__ == '__main__':
    app.run(debug=True)

2024-01-01 23:12 UTC, Adioos5 requested changes
Uwagi opisałem już wcześniej

2024-01-02 18:24 UTC, Adioos5 approved these changes

2024-01-02 18:36 UTC, merged